### ISSUE TITLE
Synfixes brokes scenarios

### ISSUE THREAD

**Issue by yarik2720** [Balimbanana/SM-Synergy#1]
ep2_outland_10a dog not removes crashed ship and runs away
ep2_outland_11:
Lamarr model creates several time, so i can see three models stucked
![20180902102409_1](https://user-images.githubusercontent.com/1839978/44953192-68b9be00-ae9a-11e8-8b0a-c091b9681d1a.jpg)
Magnusson didn't see that player already near him

more will ba added after playing all trough

**Comment by Balimbanana** [comment]
Added accounting for `generic_actor` and `generic_monster` which fixes these scenarios. Thanks for the report.
