### ISSUE TITLE
First-Person death issues

### ISSUE THREAD

**Issue by Quesoteric** [Balimbanana/SM-Synergy#16]
Normally the FPD plugin works fine, but if you get gibbed your camera is set to world origin. You could probably fix this by attaching the camera to the gib head model, but I was also pointed to UtilFixes in the Friendly Crowbar discord [here](https://github.com/ReservedRegister/SourceEngineReverseEngineering/blob/a35ff089710e680b3f40eb50875cc565da3e7e36/ext_main.cpp#L2607) to disable gibbing. However, I never was able to disable it.

**Comment by Balimbanana** [comment]
This should be resolved as of the latest commit (at the time of posting): https://github.com/Balimbanana/SM-Synergy/commit/a8de754778fccda8089da971eff74639383bf6fe
