### ISSUE TITLE
[SYNMODES] Survival mode has no fallback for resetting

### ISSUE THREAD

**Issue by Quesoteric** [Balimbanana/SM-Synergy#17]
Not really a bug to say, but having `sm_resetmode 0` and not having a valid save will spit out the message `Failed to restore - no valid autosave file found!` (sometimes, most of the time it does though) into the console.  And then, (assuming that mp_respawndelay = 0) the game will be softlocked. The only time this will likely happen is if 
1. All players die at the VERY start of a new map somehow
2. Save system doesn't decide to save for some reason for a long period after a new map
The latter depends on the map, which some save quickly and others take quite some time to save

**Comment by Balimbanana** [comment]
Ah, I should be able to check for if an autosave exists and just respawn players in that case I think.
