### ISSUE TITLE
Hyperspawn

### ISSUE THREAD

**Issue by nieumiemwymyslicnazwy** [Balimbanana/SM-Synergy#18]
I tried using hyperspawn plugin, but sometimes i spawn without weapons. pls help

**Comment by Balimbanana** [comment]
I don't manage HyperSpawn. But if you would like instant spawn, you can have it in SynModes by CVar `sm_instspawn 1` (set in synergy\cfg\sourcemod\synmodes.cfg) which has a lot of fixes/adjustments for such situations.

**Comment by nieumiemwymyslicnazwy** [comment]
Thanks man

**Comment by nieumiemwymyslicnazwy** [comment]
I have a question. How to spawn on player?

**Comment by nieumiemwymyslicnazwy** [comment]
Does this plugin have spawn on player?

**Comment by nieumiemwymyslicnazwy** [comment]
I have a problem. When i spawn somewhere else than map start, i don't have any weapons, but the weapons are on the map start :/

**Comment by nieumiemwymyslicnazwy** [comment]
> I have a problem. When i spawn somewhere else than beginning of the map, i don't have any weapons, but i found them at the map start :/
Found out that weapons spawn on checkpoint in which you joined
![20240508155611_1](https://github.com/Balimbanana/SM-Synergy/assets/165325627/4d531b56-d8f8-4557-9092-3392c51f5a74)

**Comment by Balimbanana** [comment]
Are you using SynModes for instant spawn and this is happening? If so, did you also remove or disable HyperSpawn?

**Comment by nieumiemwymyslicnazwy** [comment]
I don't know why, but i always get respawn instantly, even without sm_instspawn turned to 1

**Comment by nieumiemwymyslicnazwy** [comment]
ehh

**Comment by nieumiemwymyslicnazwy** [comment]
Hello?

**Comment by nieumiemwymyslicnazwy** [comment]
Hello?

**Comment by nieumiemwymyslicnazwy** [comment]
Still having this problem :/

**Comment by nieumiemwymyslicnazwy** [comment]
I figured out that i only have this problem on d2_coast_08

**Comment by Balimbanana** [comment]
The only thing I can think of at the moment for those issues is that you need the updated EDTs from here: https://github.com/yarik2720/Synergy-SM
There was an issue with many of the spawn points throughout HL2, Ep1 and Ep2 for spawn points clipping in to the ground which causes you to not spawn with any weapons. *Normally* if you are running SynFixes and SynModes, it will fix the equipment just after spawning if your equipment spawned out of the world.

**Comment by nieumiemwymyslicnazwy** [comment]
I installed the updated EDTs, SynFixes but it still doesn't work. Also i think the guy who wrote "How to use" issue has the same problem

**Comment by nieumiemwymyslicnazwy** [comment]
And i don't know why but instant spawn is turned on even when sm_instspawn is on 0

**Comment by Balimbanana** [comment]
I would need more information.
What is your directory tree for how you installed the updated EDT's?
Are you running Linux or Windows?
Which branch of Synergy are you running, 56.16, dev, portal, or twitch?
What is your full plugin list on server, use `sm plugins list`
Do you have more configurations set in Synergy/synergy/cfg/sourcemod that could be interfering with other mechanics or CVars?

**Comment by nieumiemwymyslicnazwy** [comment]
1. serwer\steamapps\common\Synergy\synergy\maps
2. Windows
3. 56.16
4.  01 "Admin File Reader" (1.11.0.6956) by AlliedModders LLC
    02 "Admin Help" (1.11.0.6956) by AlliedModders LLC
    03 "Admin Menu" (1.11.0.6956) by AlliedModders LLC
    04 "Anti-Flood" (1.11.0.6956) by AlliedModders LLC
    05 "Basic Ban Commands" (1.11.0.6956) by AlliedModders LLC
    06 "Basic Chat" (1.11.0.6956) by AlliedModders LLC
    07 "Basic Comm Control" (1.11.0.6956) by AlliedModders LLC
    08 "Basic Commands" (1.11.0.6956) by AlliedModders LLC
    09 "Basic Info Triggers" (1.11.0.6956) by AlliedModders LLC
    10 "Basic Votes" (1.11.0.6956) by AlliedModders LLC
    11 "Client Preferences" (1.11.0.6956) by AlliedModders LLC
    12 "Fun Commands" (1.11.0.6956) by AlliedModders LLC
    13 "Fun Votes" (1.11.0.6956) by AlliedModders LLC
    14 "MapChooser" (1.9.0.6281) by AlliedModders LLC
    15 Disabled: "Nextmap" (1.11.0.6956) by AlliedModders LLC
    16 "Player Commands" (1.11.0.6956) by AlliedModders LLC
    17 "Reserved Slots" (1.11.0.6956) by AlliedModders LLC
    18 "Player-Teleport by Dr. HyperKiLLeR" (1.2.0.2) by Dr. HyperKiLLeR Edited by Balimbanana for Synergy
    19 "Sound Commands" (1.11.0.6956) by AlliedModders LLC
    20 "SynFixes" (1.20011) by Balimbanana
    21 "SynModes" (1.60) by Balimbanana
    22 "SynFixesSpawnInVehicle" (1.23) by Balimbanana
    23 "CCreateVehicle" (1.18) by Balimbanana
5. I looked up and i don't see any more configurations that could interfer with other game mechanics

**Comment by nieumiemwymyslicnazwy** [comment]
From what i now weapons spawn only on the start of the map

**Comment by Balimbanana** [comment]
What do you have in your Synergy\synergy\cfg\sourcemod\synmodes.cfg? All of those configs are run every map change, so even if you change `sm_instspawn 0` during the map, it will reset to which ever is in those configs. I can't seem to replicate the spawning always being on. I also seem to always spawn with equipment on d2_coast_08 at the different spawn points throughout the map.
Maybe you could try changing `synmodes_manageequipment` to which ever setting it is not currently in the synmodes.cfg then change the map and see if it does anything different.
Which listed server are you referring to?

**Comment by nieumiemwymyslicnazwy** [comment]
i'm reffering to in-game server creation

**Comment by nieumiemwymyslicnazwy** [comment]
// This file was auto-generated by SourceMod (v1.11.0.6956)
// ConVars for plugin "synmodes.smx"


// -
// Default: "1"
mp_autoteambalance "1"

// Disable fall damage.
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "1.000000"
mp_disablefalldamage "0"

// Song or sound to play every round.
// -
// Default: "music/hl2_song14.mp3"
mp_dmsoundtrack "music/hl2_song14.mp3"

// Volume of the song to play every round. Goes from 0 to 100.
// -
// Default: "50"
// Minimum: "0.000000"
// Maximum: "100.000000"
mp_dmsoundtrack_volume "50"

// How many seconds to keep players frozen when the round starts.
// -
// Default: "6"
// Minimum: "1.000000"
// Maximum: "60.000000"
mp_freezetime "6"

// Number of seconds to delay before restarting a round after a win.
// -
// Default: "5.0"
// Minimum: "1.000000"
// Maximum: "60.000000"
mp_round_restart_delay "5.0"

// How many minutes each round lasts. (0 for no time limit)
// -
// Default: "2.5"
// Minimum: "0.000000"
// Maximum: "60.000000"
mp_roundtime "2.5"

// Teams are unbalanced when one team has this many more players than the other team. (0 disables check)
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "30.000000"
mp_teams_unbalance_limit "1"

// Allow instant spawn and time spawn to spawn players on other players at trigger_changelevel
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "1.000000"
sm_allowendspawn "0"

// Allows spawning inside choreo vehicles.
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
sm_choreovehiclespawn "1"

// -
// Default: "coop"
sm_gamemodeset "coop"

// Instspawn, default is 0
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "2.000000"
sm_instspawn "0"

// Force player spawn after instspawntime.
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "1.000000"
sm_instspawnforce "0"

// Instspawn time, default is 10
// -
// Default: "10"
// Minimum: "0.000000"
sm_instspawntime "0"

// Reset mode for survival gamemode. 0 is reload checkpoint, 1 is reload map, 2 is respawn all players.
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "2.000000"
sm_resetmode "0"

// Increases awareness of enemies.
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "2.000000"
syn_extraaggro "0"

// Shows debug messages for SynModes.
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "1.000000"
synmodes_debug "0"

// SynModes will handle equipping the player upon spawning them.
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
synmodes_manageequipment "0"

// Replaces voice menu with custom one.
// -
// Default: "1"
// Minimum: "0.000000"
// Maximum: "1.000000"
synmodes_replacevoicemenu "1"

**Comment by nieumiemwymyslicnazwy** [comment]
I always have this problem on d2_coast_08

**Comment by nieumiemwymyslicnazwy** [comment]
Tried changing synmodes_manageequipment - still same issue

**Comment by nieumiemwymyslicnazwy** [comment]
On which version of sourcemod should it work?

**Comment by nieumiemwymyslicnazwy** [comment]
I don't know, maybe i installed server wrong or something. I'm not really sure

**Comment by nieumiemwymyslicnazwy** [comment]
Tried SynModes with your batch server instalation and it still have the same bug when the weapons aren't spawning where they supposed to

**Comment by nieumiemwymyslicnazwy** [comment]
Now sourcemod doesn't want to work I get this error 
Unable to load plugin "addons/metamod/bin/win64/server"

**Comment by nieumiemwymyslicnazwy** [comment]
I reinstalled the server and now sourcemod won't load :/

**Comment by nieumiemwymyslicnazwy** [comment]
Hello?

**Comment by nieumiemwymyslicnazwy** [comment]
also how to get hyperspawn working on twitch branch (using your script it works but when i installed it manually it doesn't work)

**Comment by nieumiemwymyslicnazwy** [comment]
ok nvm I fixed all up turned out that when running on twitch beta items respawn correctly

**Comment by nieumiemwymyslicnazwy** [comment]
I have a question:
How to add workshop addons and gamebanana mods to dedicated server ?

**Comment by Balimbanana** [comment]
> also how to get hyperspawn working on twitch branch (using your script it works but when i installed it manually it doesn't work) and how to get working synfixesdev because it always gives me error

A lot of things are already set up through the scripts to use the specific versions of SourceMod/Metamod, perform links and fixes to the game and acquire all the dependencies for plugins that are listed in it.
