### ISSUE TITLE
FastDL

### ISSUE THREAD

**Issue by nieumiemwymyslicnazwy** [Balimbanana/SM-Synergy#22]
Hey, do you know how to make fastdl? I tried making one on github but it doesn't work

**Comment by yarik2720** [comment]
for fastdl you must have web-server on http protocol, that not forces redirect to use https, because game doesn't support it.
You can find more info on AlliedModders forum: https://forums.alliedmods.net/showthread.php?p=2732135

**Comment by nieumiemwymyslicnazwy** [comment]
Do you know any good web hosters?

**Comment by nieumiemwymyslicnazwy** [comment]
how to make custom plyaer models download?
