### ISSUE TITLE
Alyx AI stuck.

### ISSUE THREAD

**Issue by FlowerShopGuy** [Balimbanana/SM-Synergy#3]
Hello, I found an issue with a plugin "synsaverestore.smx", Alyx AI stuck when level changes after  d2_prison_08 to d3_c17_01, she just stand and doing nothing, if you restart the level then everething gose fine. Without this plugin evething is ok.

**Comment by Balimbanana** [comment]
It *should* be fixed now in the latest SynSaveRestore.

**Comment by FlowerShopGuy** [comment]
No, still don't works for me.

**Comment by FlowerShopGuy** [comment]
No, still don't works for me.

**Comment by Balimbanana** [comment]
I will check a couple other possibilities.

**Comment by Balimbanana** [comment]
Also, do you have sm_transitiondebug set to 1? Maybe it will say if it is transitioning something that it shouldn't.

**Comment by FlowerShopGuy** [comment]
No, I've never used this command, I will test with it right now.

**Comment by Balimbanana** [comment]
I wasn't able to replicate the issue on a local server. Do you have EntTools as well?
You could use it to determine a few things. When it happens, use:
`listents alyx` and if two come up, that might be the issue. You can then also try:
`cinp alyx StartScripting` and see if it resumes, if it does then I can try to make a fallback.

**Comment by FlowerShopGuy** [comment]
I don't have "EntTools", connect to my server 93.125.104.2:27015 - password "gman" and we’ll come up with something.

**Comment by FlowerShopGuy** [comment]
Sorry, I have Enttools.

**Comment by Balimbanana** [comment]
Fixed in 2.02
