### ISSUE TITLE
Black Mesa Source And Improved Xen Support File Install Fail

### ISSUE THREAD

**Issue by Elliot60501** [Balimbanana/SM-Synergy#4]
So installing the main base for BMS works but when it reaches the part where it is installing the support files via steamcmd, it gives the error that "'steamcmd.exe' is not recognized as an internal or external command, operable program or batch file." When doing the script fix it gives the same error, here's the full command prompt output:

bms (This is what I typed to select BMS)
BMS is already installed.
Press enter to apply script fix if you need to.
Press any key to continue . . . (Here I hit enter)

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21

Scanning the drive for archives:
1 file, 160573 bytes (157 KiB)

Extracting archive: .\bmscripts.zip
--
Path = .\bmscripts.zip
Type = zip
Physical Size = 160573

Everything is Ok

Folders: 3
Files: 103
Size:       836055
Compressed: 160573
Downloading Synergy Support files through SteamCMD
'steamcmd.exe' is not recognized as an internal or external command,
operable program or batch file. (And here is where the problem is)

Check for any errors above, if there are any, you may need to re-run this script.
Finished installing/patching BMS for use in Synergy.

Press any key to continue . . .

I would like to note that I can still manually install the support files, I just wanted to put out this issue for those who want to use this program to install Synergy server with source mods and plugins. Note: This is an issue/problem/bug with the "InstallSourceMods.bat" file.

**Comment by Balimbanana** [comment]
I have added a check now which should get it to download SteamCMD if it isn't found at that step.

**Comment by Elliot60501** [comment]
Sorry for the late response telling you if its fixed, two things, even though the issue with SteamCMD is fixed, now the extracting archive part is now stuck in an endless loop. I know you closed this issue two days ago because of my late response, there is just this last issue to attend to. Quick note: I actually don't know if the SteamCMD issue is fixed because the archive extraction part is before it, so I won't know since the archive extraction is now in an endless loop.
