### ISSUE TITLE
Archive Extraction For BMS Stuck In Endless Loop

### ISSUE THREAD

**Issue by Elliot60501** [Balimbanana/SM-Synergy#5]
Two things to note, even though the issue with SteamCMD is fixed (look at issue post: https://github.com/Balimbanana/SM-Synergy/issues/4#), now the extracting archive part before SteamCMD is now stuck in an endless loop. I don't know if the SteamCMD issue is fixed because of this new issue (again see issue post: https://github.com/Balimbanana/SM-Synergy/issues/4#).

**Comment by Balimbanana** [comment]
It *should* be fixed now. It was an issue of returning to a function after not having the prerequisite files running over and over.

**Comment by Elliot60501** [comment]
Ok, strange, I downloaded a new copy of the Install Sourcemods Bat file, and after testing to see if the issue is fixed, it is still continuing to persist. Do I have to create the server again from scratch, or do I need to reinstall the entire BMS sourcemod? Again still don't know if the SteamCMD issue is fixed (see issue post: #4) because of the loop.

**Comment by Balimbanana** [comment]
Are you sure it isn't just downloading SteamCMD updates, then restarting, then downloading the support? I just tested and it seems to be working as it should.

**Comment by Balimbanana** [comment]
Are you running this on Windows 7 pre service pack 1 by any chance? It might be a feature/function of PowerShell that isn't in earlier versions of Windows 7.

**Comment by Elliot60501** [comment]
Im using a Windows 10, but do note that when I first noted the SteamCMD issue in #4, I shared you my log. Note how it says that I already have BMS installed, I'm not sure it is installed in the server though. I did have BMS installed in the steam client. This is because I had manually installed the Steam BMS support files. Could this be the issue?

**Comment by Balimbanana** [comment]
Is it still the same messages then? What is the log now?

**Comment by Elliot60501** [comment]
bms (Here I enter bms)
BMS is already installed. (This is because it is installed in the steam client, I'll uninstall the manual source file BMS download just to be sure)
Press enter to apply script fix if you need to. (Here I'm hitting enter so it can go over and fix itself)
Press any key to continue . . .

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21

Scanning the drive for archives:
1 file, 160573 bytes (157 KiB)

Extracting archive: .\bmscripts.zip
--
Path = .\bmscripts.zip
Type = zip
Physical Size = 160573

Everything is Ok

Folders: 3
Files: 103
Size:       836055
Compressed: 160573

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21

Scanning the drive for archives:
1 file, 160573 bytes (157 KiB)

Extracting archive: .\bmscripts.zip
--
Path = .\bmscripts.zip
Type = zip
Physical Size = 160573

Everything is Ok

Folders: 3
Files: 103
Size:       836055
Compressed: 160573
(Now note how there are two 7-Zip dialoge, this isn't a human error with me copying, this keeps going forever, no stop. Also note it is extracting the same zip over and over again. This shows us its stuck in a loop.)

**Comment by Elliot60501** [comment]
Oh, the script is located in the same directory where SteamCMD and the server itself is being downloaded. I should also have the proper read and write permissions.

**Comment by Balimbanana** [comment]
Try running update on the first prompt, what comes up for the first message "Found sourcemods directory here:"?

**Comment by Elliot60501** [comment]
Here it is directly from the prompt:
update
Updated...
Found sourcemods directory here: c:\program files (x86)\steam\steamapps\sourcemods

**Comment by Balimbanana** [comment]
Hmm, it looks like it should be working like that. Is it still looping over and over on the updated one?

**Comment by Elliot60501** [comment]
Which one the first prompt update? Or the BMS update by pressing enter?

**Comment by Balimbanana** [comment]
The BMS scripts update.

**Comment by Balimbanana** [comment]
Also, just updated it again. It might have been an implied path issue.

**Comment by Elliot60501** [comment]
What I do when I replace the bat scripts when you update them is that I just download a new zip of all of them, unzip them, and replace the older ones with the new ones. That should work, right?

**Comment by Elliot60501** [comment]
Also, the update that isn't looping is the main InstallSourcemods.bat prompt update.

**Comment by Elliot60501** [comment]
Ok so I tested both updates, same results. :(

**Comment by Balimbanana** [comment]
I can't replicate the loop issue, Is it still doing it on the latest version?

**Comment by Elliot60501** [comment]
Do you have a check that checks to see if the zip is extracted? Where would the zip be located if this worked properly? One more thing, I might need to reload the GitHub page to get the latest version. That is why I might be having trouble.

**Comment by Balimbanana** [comment]
Updating either way *should* work, although the full archive will take a few more seconds after an update has been pushed for the archive to update.
I don't really see anything that would be recalling the extraction. The scripts zip is removed after it is extracted, so it would have to be constantly re-downloading and re-applying if the loop is doing that. It might be an issue in 7-Zip stuck retrying the archive somehow.
I have just updated it again with a bit more info which it should be displaying if something is going wrong.

**Comment by Elliot60501** [comment]
If you look back at my logs I've shared, it does say that "Everything is OK". This should mean it worked right? It should continue, let's hope it isn't a 7-Zip issue because you won't be able to fix that right?

**Comment by Balimbanana** [comment]
It *should* be supposedly.

**Comment by Elliot60501** [comment]
Ooooo! Something interesting is up now, it is still looping, but now it says that SteamCMD failed to find the workshop update/install and that it is now retrying.
Here is the log:

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21

Scanning the drive for archives:
1 file, 160573 bytes (157 KiB)

Extracting archive: .\bmscripts.zip
--
Path = .\bmscripts.zip
Type = zip
Physical Size = 160573

Everything is Ok (Here it says it successfully did it)

Folders: 3
Files: 103
Size:       836055
Compressed: 160573
Failed to find SteamCMD for workshop update/install. Attempting to re-download... (Interesting!)

Do you think it is repeating because of this SteamCMD issue? It might be the same one from before, except I checked back to the log I posted in the previous issue post and it was because it couldn't find SteamCMD. Let me paste the previous log from before:

bms (This is what I typed to select BMS)
BMS is already installed.
Press enter to apply script fix if you need to.
Press any key to continue . . . (Here I hit enter)

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21

Scanning the drive for archives:
1 file, 160573 bytes (157 KiB)

Extracting archive: .\bmscripts.zip
Path = .\bmscripts.zip
Type = zip
Physical Size = 160573

Everything is Ok

Folders: 3
Files: 103
Size: 836055
Compressed: 160573
Downloading Synergy Support files through SteamCMD
'steamcmd.exe' is not recognized as an internal or external command,
operable program or batch file. (And here is where the problem is)

Check for any errors above, if there are any, you may need to re-run this script.
Finished installing/patching BMS for use in Synergy.

Press any key to continue . . .

What do think is happening from this new situation?

**Comment by Elliot60501** [comment]
I think I'll uninstall the support files themself I manually installed off of your source support file list, then it might just work properly.

**Comment by Elliot60501** [comment]
Ok unsubscribed from it, I'll uninstall BMS off of the main steam client, then I'll try again.

**Comment by Balimbanana** [comment]
If the script is being run from the same directory as SteamCMD, it should now detect that and use that one instead.

**Comment by Elliot60501** [comment]
Yeah, but you fixed that, it has detected SteamCMD and run it but now it can't seem to find workshop content.

**Comment by Elliot60501** [comment]
WOAH! Got it to work!

**Comment by Elliot60501** [comment]
Ok even more strange it now works properly no matter what, one more bug is if you want to hit any other key to continue, it acts like just hitting enter and go through the script fix process.

**Comment by Elliot60501** [comment]
Now I just need to run the server to verify that it works, this might take some time.

**Comment by Elliot60501** [comment]
Yes! It is now working properly, thanks for the help. This was also probably helpful for those who have the same problem with BMS or other sourcemods.

**Comment by Elliot60501** [comment]
So in conclusion, let the InstallSource.bat script install the source files for you instead of you installing it manually. If you think there was something else preventing it from working you should comment it for others to know how to solve this if it ever happens again.
