### ISSUE TITLE
Alyx not spawning in d2_prison_08

### ISSUE THREAD

**Issue by Aksumxd** [Balimbanana/SM-Synergy#8]
A similar issue was discussed earlier [here](https://github.com/Balimbanana/SM-Synergy/issues/3). 

First time we transitioned from d2_prison_07 to 08 the game crashed. Next time we loaded up the level alyx was nowhere to be seen. 

```
] listents alyx
No entities found with either classname or targetname of alyx
] cinp alyx StartScripting
alyx StartScripting
No entities found with either classname or targetname of alyx
```
It seems that she hasn't spawned in at all. Maybe this could be fixed through SynFixes though I'm not really sure.

**Comment by Balimbanana** [comment]
Do you have the updated EDT's as well? https://github.com/yarik2720/Synergy-SM

It could potentially be added as a static check on some maps in SynFixes if the updated EDTs don't work.

**Comment by Balimbanana** [comment]
Static setups has been added in the latest commit.
